name: build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust
        run: rustup show
      - name: install nextest
        uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: Check code format
        run: cargo fmt -- --check
      - name: Check the package for errors
        run: cargo check --workspace
      - name: Lint rust sources
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Execute rust tests
        run: cargo nextest run --all-features --no-tests=pass

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # keep in sync with rust-version in Cargo.toml
      - name: Install MSRV toolchain
        run: rustup toolchain install 1.85.0 --profile minimal --no-self-update
      - name: Check against MSRV
        run: cargo +1.85.0 check --workspace --all-features

  release:
    needs: build-rust
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.git-cliff.outputs.content }}
